[colors.bright]
black = "#7f8c8d"
blue = "#3daee9"
cyan = "#16a085"
green = "#1cdc9a"
magenta = "#8e44ad"
red = "#c0392b"
white = "#ffffff"
yellow = "#fdbc4b"

[colors.dim]
black = "#31363b"
blue = "#1b668f"
cyan = "#186c60"
green = "#17a262"
magenta = "#614a73"
red = "#783228"
white = "#63686d"
yellow = "#b65619"

[colors.normal]
black = "#232627"
blue = "#1d99f3"
cyan = "#1abc9c"
green = "#11d116"
magenta = "#9b59b6"
red = "#ed1515"
white = "#fcfcfc"
yellow = "#f67400"

[colors.primary]
#bright_background = "#000000"
bright_foreground = "#ffffff"
#dim_background = "#31363b"
dim_foreground = "#eff0f1"
background = "#232627"
foreground = "#fcfcfc"

[env]
WINIT_X11_SCALE_FACTOR = "1"

[font]
size = 9

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"

[selection]
save_to_clipboard = false

[[hints.enabled]]
command = "xdg-open" # On Linux/BSD
# command = "open" # On macOS
# command = { program = "cmd", args = [ "/c", "start", "" ] } # On Windows
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
